name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      ENVIRONMENT: ${{secrets.ENVIRONMENT}}
    steps:
      - name: Checkout code and copy to workspace
        uses: actions/checkout@v4

      - name: Operating System-(OS) update
        run: sudo apt update

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry and dependencies
        run: |
          pipx install poetry
          poetry install --no-root

      - name: Run tests
        run: poetry run task test